[tool.poetry]
name = "smaregi-price-converter"
version = "0.1.0"
description = ""
authors = ["v3vapp <v3v.app@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
